### ISSUE TITLE
Additional fields for manual url

### ISSUE THREAD

**Issue by engram-design** [am-impact/amnav#12]
While building a mega-menu style menu, I've come across the need to be able to customise headings inside the dropdown menu. What would really help with this, is if an additional field (title or class maybe?) was available to enter this information.

You can see what I mean from the below image - 
![screen shot 2014-12-13 at 2 20 35 pm](https://cloud.githubusercontent.com/assets/1221575/5422407/3e0aeec8-82d3-11e4-8441-506752b72e2c.png)

Where the inner "See & Do" heading would need to be customised to a desired string. Can certainly be done statically within the template, but would be great for a client to be able to edit this from the CP.

I've achieved something similar before with NavEE, as it offers so-so many extra fields for customisation of menu items.

**Comment by hubertprein** [comment]
@engram-design A very late reply on this, sorry about that.

There have been a few releases after your issue was submitted. By now you can add a custom class to nodes you desire. Otherwise you can always use **getNavRaw** to get your desired result. Hope this solves your problem in future projects.

I'm closing this issue for now.
