### ISSUE TITLE
Cache Breaking

### ISSUE THREAD

**Issue by brettburwell** [am-impact/amnav#62]
When I add a new node to my navigation it doesn't appear to be breaking Craft's caching. So the new link isn't added to / reflected on the site until another action in the CMS (manually clearing the cache, updating an entry, etc.) empties the cache. 

Is there something I need to do on the configuration / templating side of things to ensure the cache refreshes when the nav is updated?

I've read through the docs and poked around all the config settings, but can't seem to sort it out. Is it correct to assume that the cache should be breaking when the nav is updated? Or is the plugin not configured to do that?

**Comment by hubertprein** [comment]
The plugin is indeed not configured to do that. You must have a cache tag placed around the navigation then, or you shouldn't have this issue. We don't use a cache tag around our navigations for our clients, since we haven't seen any performance issues when using this plugin. So I'd recommend you try to remove the cache tag, and see what your page speed is :)

**Comment by brettburwell** [comment]
Thanks for the followup Hubert. That's helpful to know. We've got a static caching plugin in place, so it's not quite as simple as removing cache tags. 

But I realize that's an edge case... so it's good to know I'm not just missing something or running into a bug.
