### ISSUE TITLE
Feature request: Adding a locale

### ISSUE THREAD

**Issue by chrisrowe** [am-impact/amnav#66]
When adding a locale my assumption would be that any navigations set up would be cloned over using the default locales (as per entries/sections).

Unless I'm missing something it appears this doesn't happen.

**Comment by hubertprein** [comment]
I understand that one would expect that, but there's more work behind that. Because then one would also expect, that when adding an element to the navigation, it would be added to all enabled locales. Which is not what you always want. You might have different navigations per locale, so the same goes when adding a new locale.

I'll keep the issue open, that perhaps when we find a proper solution in the future, I'll update it here.

**Comment by brianjhanson** [comment]
Maybe at least a button that lets you copy a nav from a different locale as a starting point?

**Comment by kevinmeyvaert** [comment]
Any progression on this issue? Or maybe extra docs on using AmNav on localized sites? I can't seem to get it working for now.
